COMPONENT_DEPENDS := ArduinoJson6
COMPONENT_SRCDIRS := $(call ListAllSubDirs,$(COMPONENT_PATH)/src)

COMPONENT_RELINK_VARS += IOCONTROL_MAX_REQUESTS
ifneq (,$(IOCONTROL_MAX_REQUESTS))
COMPONENT_CXXFLAGS += -DIOCONTROL_MAX_REQUESTS=$(IOCONTROL_MAX_REQUESTS)
endif
